# Generated by Django 4.2.13 on 2024-07-14 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="Group",
            new_name="group",
        ),
    ]
