# Generated by Django 4.2.13 on 2024-07-23 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_contact_is_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_sending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.group')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_sending.emailtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
