# Generated by Django 4.2.13 on 2024-07-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sending', '0002_emailsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsession',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='emailsession',
            old_name='template',
            new_name='template_id',
        ),
    ]
