version: '3.9'

services:
  web:
    container_name: liftsmail
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  cache:
    container_name: cache
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A liftsmail worker --loglevel=info
    working_dir: /app
    restart: always
    volumes:
      -  .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
  
  celery-beat:
    build: .
    command: celery -A liftsmail beat --loglevel=info
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    depends_on:
      - cache
      - web
      - celery
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1